### ISSUE TITLE
get_loc keyError while running pyShore

### ISSUE THREAD

**Issue by Catherinedune** [MirandaLv/pyShore#2]
CoastalStructurePrediction tool ran for about 5 in. before getting a keyerror, text below:

![image](https://github.com/MirandaLv/pyShore/assets/140836972/5b124eb2-e49d-428c-913c-04b2be7ef5f1)

**ArcGIS Pro 3.1.2  using:**
Python 3.9.11
 ESRI/Installed deep-learning-frameworks 
PyTorch 1.8.2
Pandas 1.4.4
Tensorflow-gpu 2.7
keras-gpu 2.7 
Pillow 9.5.0
fastai 1.0.63
scikit-image 0.17.2

**Comment by MirandaLv** [comment]
This error is a result of the discrepancy between the CRS of the image tiles and the shoreline file. Please ensure that the CRS is set to EPSG:4326.
